import { NextResponse } from 'next/server';

export async function GET() {
  const t = Date.now();
  const ago = (ms: number) => new Date(t - ms).toISOString();

  return NextResponse.json({
    overall: 'Degraded',
    checkedAt: new Date(t).toISOString(),
    groups: [
      {
        name: 'F&O Platform',
        components: [
          {
            id: 'fno-prod',
            name: 'F&O Availability',
            probeType: 'fno',
            status: 'Healthy',
            responseTimeMs: 892,
            message: 'F&O OData available (892 ms)',
            checkedAt: ago(40_000),
            lastChangedAt: null,
          },
          {
            id: 'fno-exceptions',
            name: 'F&O Exception Rate',
            probeType: 'appinsights',
            status: 'Healthy',
            responseTimeMs: 0,
            message: 'Exceptions: 2.0/30 min (nominal)',
            checkedAt: ago(5 * 60_000),
            lastChangedAt: null,
          },
          {
            id: 'fno-batch',
            name: 'F&O Batch Health',
            probeType: 'appinsights',
            status: 'Healthy',
            responseTimeMs: 0,
            message: 'Batch failures: 0.0/30 min (nominal)',
            checkedAt: ago(5 * 60_000),
            lastChangedAt: null,
          },
        ],
      },
      {
        name: 'Integrations',
        components: [
          {
            id: 'crm-api',
            name: 'CRM Integration',
            probeType: 'http',
            status: 'Healthy',
            responseTimeMs: 145,
            message: 'HTTP 200 in 145 ms',
            checkedAt: ago(45_000),
            lastChangedAt: null,
          },
          {
            id: 'erp-connector',
            name: 'ERP Connector',
            probeType: 'http',
            status: 'Degraded',
            responseTimeMs: 3200,
            message: 'Response slow (3200 ms) — threshold 2000 ms',
            checkedAt: ago(30_000),
            lastChangedAt: ago(8 * 60_000),
          },
          {
            id: 'logistics-api',
            name: 'Logistics API',
            probeType: 'http',
            status: 'Healthy',
            responseTimeMs: 212,
            message: 'HTTP 200 in 212 ms',
            checkedAt: ago(55_000),
            lastChangedAt: null,
          },
          {
            id: 'payment-gateway',
            name: 'Payment Gateway',
            probeType: 'http',
            status: 'Healthy',
            responseTimeMs: 390,
            message: 'HTTP 200 in 390 ms',
            checkedAt: ago(20_000),
            lastChangedAt: null,
          },
          {
            id: 'ecommerce-api',
            name: 'E-Commerce API',
            probeType: 'http',
            status: 'Healthy',
            responseTimeMs: 178,
            message: 'HTTP 200 in 178 ms',
            checkedAt: ago(35_000),
            lastChangedAt: null,
          },
        ],
      },
      {
        name: 'Pipelines',
        components: [
          {
            id: 'deploy-pipeline',
            name: 'Production Deployment',
            probeType: 'devops',
            status: 'Healthy',
            responseTimeMs: 0,
            message: 'Build 20240613.4 succeeded',
            checkedAt: ago(5 * 60_000),
            lastChangedAt: null,
          },
          {
            id: 'integration-pipeline',
            name: 'Integration Sync Pipeline',
            probeType: 'devops',
            status: 'Maintenance',
            responseTimeMs: 0,
            message: 'Maintenance window — pipeline paused until 18:00',
            checkedAt: ago(5 * 60_000),
            lastChangedAt: ago(90 * 60_000),
          },
        ],
      },
      {
        name: 'Data Stores',
        components: [
          {
            id: 'byod-sql',
            name: 'BYOD Azure SQL',
            probeType: 'sql',
            status: 'Healthy',
            responseTimeMs: 23,
            message: 'SQL ping 23 ms',
            checkedAt: ago(50_000),
            lastChangedAt: null,
          },
          {
            id: 'integration-bus',
            name: 'Service Bus',
            probeType: 'servicebus',
            status: 'Healthy',
            responseTimeMs: 0,
            message: 'Queue healthy — 3 active, 0 DLQ',
            checkedAt: ago(60_000),
            lastChangedAt: null,
          },
        ],
      },
    ],
    activeIncidents: [
      {
        id: '202406/active-001',
        title: 'ERP Connector elevated latency',
        body: 'We are investigating elevated response times on the ERP Connector endpoint. Other services are unaffected.',
        status: 'investigating',
        severity: 'minor',
        affectedComponents: ['erp-connector'],
        createdAt: ago(12 * 60_000),
        resolvedAt: null,
      },
      {
        id: '202406/active-002',
        title: 'Integration Sync Pipeline — scheduled maintenance window',
        body: 'The Integration Sync Pipeline is paused for a planned infrastructure update. Data sync will resume after 18:00.',
        status: 'monitoring',
        severity: 'maintenance',
        affectedComponents: ['integration-pipeline'],
        createdAt: ago(90 * 60_000),
        resolvedAt: null,
      },
    ],
  });
}
